<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1</TargetFrameworks>
    <OutputPath>..\bin\app</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotLiquid" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThirdPartyLibraries.Domain\ThirdPartyLibraries.Domain.csproj" />
    <ProjectReference Include="..\ThirdPartyLibraries.Shared\ThirdPartyLibraries.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\Docs\default.appsettings.json" Link="Template\appsettings.json" />
    <EmbeddedResource Include="..\..\Docs\default.npmjs.com.ReadMeTemplate.txt" Link="Template\npmjs.com.ReadMeTemplate.txt" />
    <EmbeddedResource Include="..\..\Docs\default.nuget.org.ReadMeTemplate.txt" Link="Template\nuget.org.ReadMeTemplate.txt" />
    <EmbeddedResource Include="..\..\Docs\default.ThirdPartyNotices.Template.txt" Link="Template\ThirdPartyNotices.Template.txt" />
    <EmbeddedResource Include="..\..\Docs\default.root.ReadMeTemplate.txt" Link="Template\Root.ReadMeTemplate.txt" />
  </ItemGroup>

</Project>
